using Arch.Core;
using System.Collections.Generic;

namespace MUD.Rulesets.D20.Components
{
    /// <summary>
    /// Stores messages generated by game systems (combat, room events) 
    /// waiting to be sent to the player's client.
    /// </summary>
    public struct OutputMessageComponent
    {
        public List<string> Messages;
    }
}